apache_listen_port: 80
# apache_vhosts:
  # # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
  # - servername: "local.dev"
    # documentroot: "/var/www/html"
apache_state: started