---
# compute-video-demo-ansible
- name: Create jmeter instances
  hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/jenkinszone
    
  tasks:
    - name: Bring up the jmeter instances
      gce:
        instance_names: "{{ jmeter_name }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        zone: "{{ jenkins_zone }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      register: jmeter_host
      
      
    - name: Allow HTTP  4445 for jmeter traffic
      gce_net:
        fwname: jmeter-traffic
        name: default
        allowed: tcp:4445
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      
  post_tasks:
    - name: Wait for SSH for jmeter instances
      wait_for: delay=1 host={{ item.public_ip }} port=22 state=started timeout=30
      with_items: "{{ jmeter_host.instance_data }}"
    - name: Save host data for jmeter zone
      add_host: hostname={{ item.public_ip }} groupname=gce_jmeter_ips
      with_items: "{{ jmeter_host.instance_data }}"  
