# Example Playbook
- name: Compute Engine Instance Examples
  hosts: local
  connection: local
  vars_files:
    - vars/gcp_auth  
  tasks:
    - name: delete test-instances
      # Basic termination of instance.
      gce:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        instance_names: micro1
        #instance_names: micro1,micro2
        zone: us-central1-a
        state: absent
      tags:
        - delete
       